### ISSUE TITLE
Incorrect operation of the unidecode_expect_ascii method (python 3.x)

### ISSUE THREAD

**Issue by mazurenkomm** [avian2/unidecode#45]
The library is used in wagtail cms, when setting up the search, I noticed that the Cyrillic text is converted to transliteration. For the spelling dictionary this was unacceptable.

**Comment by mazurenkomm** [comment]
I use utf8 encoding, so "bytestring = string.encode ('ASCII')" causes an exception. The exception is processed, and returns a string in transliteration. next is a check on the python version, in and Python 3 unicode is used. I need the original string, but the exception handling has already returned it in transliteration.

**Comment by avian2** [comment]
What you describe is exactly how the `unidecode_expect_ascii` is supposed to work. This function takes a Unicode string and returns an ASCII string. If the string can be encoded to ASCII without an error, then no transliteration is necessary (since string is obviously already in ASCII). In the other case, transliteration from Unicode to ASCII is necessary. If you need the original (non-ASCII) string, you should not call `unidecode_expect_ascii` at all.

**Comment by mazurenkomm** [comment]
For python 3, transliteration is not required. The string must be returned in the same format, because Python 3 uses Unicode by default. Otherwise, this function does not make sense.

**Comment by mazurenkomm** [comment]
I'm sorry, I'm wrong
