### ISSUE TITLE
UTF-16 problems

### ISSUE THREAD

**Issue by niloct** [avian2/unidecode#56]
First of all, thanks for this tool.

I'm trying to decode `UTF-16` escaped strings to no avail.

For instance, `\u00c1` is converted to A instead of Á:

```
>>> import unidecode
>>> unidecode.unidecode('\u00c1')
'A'
>>> unidecode.unidecode(u'\u00c1')
'A'
```

(I've used https://www.branah.com/unicode-converter to verify)

Is there an option to specify the `UTF-16` encoding ?

Thanks.

**Comment by avian2** [comment]
There is no option to specify UTF-16 encoding because Unidecode provides "**ASCII** transliterations". "A" output is correct. If you want your string encoded as UTF-16 there is no transliteration needed since UTF-16 can encode the "Á" character.

Please read the [Unicode HOWTO](https://docs.python.org/3/howto/unicode.html) for an introduction to character encodings in Python.
