### ISSUE TITLE
Conversion can be inaccurate in the context of scientific units.

### ISSUE THREAD

**Issue by mmcdermott** [avian2/unidecode#65]
![image](https://user-images.githubusercontent.com/470751/125792041-4f37809f-b3a5-4332-89a2-8a4ee7377a32.png)
In reality, 'μmol' is _micro_ mol and mmol is _mili_ mol, so 1 mmol is 1000 μmol

'umol' would also be an acceptable transliteration in this case.

**Comment by avian2** [comment]
This won't be fixed in Unidecode, sorry.

"m" is a better ASCII transliteration for letter mu when used in Greek language. With context free replacements Unidecode can't distinguish whether the character is used as a SI prefix or part of a Greek word. 

Codepoints for SI units like ㎛ should already be transliterated as you suggest.
